"""Build and execute notebooks/01_results_anatomy.ipynb from the latest runs (outputs committed).

Usage: uv run --group notebooks python scripts/build_notebook.py
Every figure and number in the notebook is computed when it executes; the markdown cells only
frame what to look at.
"""

from __future__ import annotations

from pathlib import Path

import nbformat
from nbclient import NotebookClient

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "notebooks" / "01_results_anatomy.ipynb"

md = nbformat.v4.new_markdown_cell
code = nbformat.v4.new_code_cell

CELLS = [
    md(
        "# GridCast — anatomy of the validation results\n\n"
        "Generated by `scripts/build_notebook.py`; re-run it after a new backtest. Validation "
        "window only (the test split is locked)."
    ),
    code("""import json
from pathlib import Path
import duckdb, polars as pl, matplotlib.pyplot as plt

ROOT = Path.cwd().parent if Path.cwd().name == "notebooks" else Path.cwd()
RUNS = ROOT / "reports" / "runs"
def pick(pred):
    runs = sorted((json.loads(p.read_text()) for p in RUNS.glob("*/config.json")), key=lambda c: c["run_id"])
    runs = [c for c in runs if pred(c)]
    return runs[-1]["run_id"] if runs else None
RUN = pick(lambda c: c["split"] == "validation" and "lgbm_global" in c["models"] and "nhits" in c["models"]) \\
      or pick(lambda c: c["split"] == "validation" and "lgbm_global" in c["models"])
cfg = json.loads((RUNS / RUN / "config.json").read_text())
print("run:", RUN, "| models:", cfg["models"], "| window:", cfg["window"])
con = duckdb.connect(str(ROOT / "data" / "warehouse.duckdb"), read_only=True); con.execute("SET TimeZone='UTC'")
plt.rcParams.update({"figure.figsize": (10, 4), "axes.grid": True, "grid.alpha": 0.3})"""),
    md(
        "## 1. The benchmark itself is not always a forecast of the same quantity\n\n"
        "Signed error of the operator's day-ahead forecast by local hour, per year, for CISO — the "
        "solar-hour dip deepens every year (see `reports/data_profile.md` §5.1)."
    ),
    code("""ciso = con.sql('''select year(local_date) y, hour_number h,
    100*avg((operator_forecast_mw-demand_mw)/demand_mw) bias
  from fct_demand_hourly where ba_code='CISO' and demand_mw>0 and operator_forecast_mw is not null and hour_number<=24
  group by all order by 1,2''').pl()
fig, ax = plt.subplots()
for y in sorted(ciso["y"].unique()):
    s = ciso.filter(pl.col("y") == y); ax.plot(s["h"], s["bias"], label=str(y))
ax.axhline(0, color="k", lw=0.8); ax.set_xlabel("hour of day (local, hour ending)"); ax.set_ylabel("operator bias %")
ax.legend(ncol=4, fontsize=8); ax.set_title("CISO: operator day-ahead forecast minus reported demand"); plt.show()"""),
    code("""swpp = con.sql('''select date_trunc('month', local_date) m, 100*avg((operator_forecast_mw-demand_mw)/demand_mw) bias
  from fct_demand_hourly where ba_code='SWPP' and demand_mw>0 and operator_forecast_mw is not null
  and local_date >= date '2024-01-01' group by 1 order by 1''').pl()
fig, ax = plt.subplots(); ax.bar(swpp["m"].cast(pl.Date).cast(pl.String), swpp["bias"])
ax.set_title("SWPP: monthly operator bias % — a step change in 2025-05"); ax.tick_params(axis="x", rotation=90); plt.show()"""),
    md(
        "## 2. How far behind the operators are we?\n\nMAPE per BA for our best models and both benchmarks, same scored hours."
    ),
    code("""point = pl.read_csv(RUNS / RUN / "metrics_point.csv")
show = [m for m in ["operator", "operator_debiased", "ridge", "lgbm_global", "nhits"] if m in point["model"].to_list()]
wide = point.filter(pl.col("model").is_in(show)).pivot(on="model", index="ba_code", values="mape").sort("ba_code")
ax = wide.to_pandas().set_index("ba_code")[show].plot.bar(figsize=(11, 4)); ax.set_ylabel("MAPE %"); plt.show()
overall = pl.read_csv(RUNS / RUN / "metrics_overall.csv").filter(pl.col("model").is_in(show)).sort("mape")
overall.select("model", "hours", "mape", "mae", "bias_pct")"""),
    code("""comps = pl.read_csv(RUNS / RUN / "comparisons.csv")
comps.filter(pl.col("reference") == "operator_debiased").select(
    "ba_code", "model", "skill", "skill_low", "skill_high", "dm_p").sort("model", "ba_code")"""),
    md("## 3. Where the error is: hour of day"),
    code("""fc = pl.read_parquet(RUNS / RUN / "forecasts.parquet").filter(pl.col("model").is_in(show))
act = con.sql("select ba_code, hour_ending_utc, hour_number, demand_mw y from fct_demand_hourly").pl()
j = fc.join(act, on=["ba_code", "hour_ending_utc"]).filter(pl.col("y") > 0)
byh = j.group_by("model", "hour_number").agg((100*(pl.col("yhat")-pl.col("y")).abs()/pl.col("y")).mean().alias("mape")).sort("hour_number")
fig, ax = plt.subplots()
for m in show:
    s = byh.filter((pl.col("model") == m) & (pl.col("hour_number") <= 24)); ax.plot(s["hour_number"], s["mape"], label=m)
ax.set_xlabel("hour number (local)"); ax.set_ylabel("MAPE %, pooled over BAs"); ax.legend(); plt.show()"""),
    md("## 4. Are the intervals honest? Raw quantile heads vs rolling CQR"),
    code("""iv = pl.read_csv(RUNS / RUN / "metrics_intervals.csv")
fig, axes = plt.subplots(1, 2, figsize=(12, 4), sharey=True)
for ax, (col, nominal) in zip(axes, [("coverage_80", 80), ("coverage_95", 95)]):
    for m in sorted(iv["model"].unique()):
        s = iv.filter(pl.col("model") == m).sort("ba_code"); ax.plot(s["ba_code"], s[col], "o-", label=m)
    ax.axhspan(nominal-3, nominal+3, color="green", alpha=0.1); ax.axhline(nominal, color="green")
    ax.set_title(f"empirical coverage of the {nominal}% interval"); ax.tick_params(axis="x", rotation=45)
axes[0].legend(fontsize=7); plt.show()
iv.group_by("model").agg(pl.col("coverage_80").mean(), pl.col("coverage_95").mean(), pl.col("width_80_pct").mean()).sort("model")"""),
    md("## 5. Ablations (one change at a time, vs the production configuration)"),
    code("""abl = sorted((ROOT / "reports" / "ablations").glob("*/comparisons.csv"))
if abl:
    a = pl.read_csv(abl[-1])
    display(pl.read_csv(abl[-1].parent / "overall.csv"))
    display(a.filter(pl.col("ba_code") == "ALL"))
else:
    print("no ablation run yet")"""),
]


def main() -> None:
    nb = nbformat.v4.new_notebook(cells=CELLS)
    nb.metadata["kernelspec"] = {
        "name": "python3",
        "display_name": "Python 3",
        "language": "python",
    }
    NotebookClient(
        nb, timeout=600, kernel_name="python3", resources={"metadata": {"path": str(ROOT)}}
    ).execute()
    OUT.write_text(nbformat.writes(nb))
    errors = [
        o
        for c in nb.cells
        if c.cell_type == "code"
        for o in c.get("outputs", [])
        if o.get("output_type") == "error"
    ]
    print(f"wrote {OUT} ({len(nb.cells)} cells, {len(errors)} errors)")


if __name__ == "__main__":
    main()
